runtime: nodejs18

service_account: lichessconnector@appspot.gserviceaccount.com

env_variables:
  MONGODB_URI: "mongodb+srv://NarekBrc:Halabyan_brc@breakroomcupcluster.uudts.mongodb.net/?retryWrites=true&w=majority"
  LICHESS_TOKEN: "lip_TZezCbtaq5O1tmgXrYmM"
  JWT_SECRET: "lip_TZezCbtaq5O1tmgXrYmM"
  PORT: "8080"
  FRONTEND_URL: "https://lichess-chess-nexus.lovable.app"

# For basic scaling, use B instance class instead of F
instance_class: B1

# Choose only one scaling option
basic_scaling:
  max_instances: 10
  idle_timeout: 10m

handlers:
  # Handle CORS preflight requests
  - url: /.*
    script: auto
    secure: always

env: standard 