name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: '${{ secrets.GCP_PROJECT_ID }}'

    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v2.1.4
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Update app.yaml with secrets
      run: |
        sed -i "s|your_mongodb_uri|${{ secrets.MONGODB_URI }}|g" app.yaml
        sed -i "s|your_lichess_token|${{ secrets.LICHESS_TOKEN }}|g" app.yaml
        sed -i "s|your_jwt_secret|${{ secrets.JWT_SECRET }}|g" app.yaml
        sed -i "s|your_frontend_url|${{ secrets.FRONTEND_URL }}|g" app.yaml

    - name: Check and Create App Engine application
      run: |
        echo "Checking if App Engine exists..."
        if ! gcloud app describe > /dev/null 2>&1; then
          echo "Creating new App Engine application in us-central..."
          gcloud app create --region=us-central --project=${{ secrets.GCP_PROJECT_ID }}
        else
          echo "App Engine application already exists."
        fi

    - name: Enable necessary APIs
      run: |
        gcloud services enable appengine.googleapis.com
        gcloud services enable cloudbuild.googleapis.com

    - name: Deploy to App Engine
      run: |
        echo "Starting deployment..."
        gcloud app deploy app.yaml --quiet --project=${{ secrets.GCP_PROJECT_ID }}
        echo "Deployment completed." 