name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: '${{ secrets.GCP_PROJECT_ID }}'

    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v2.1.4
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Update app.yaml with secrets
      run: |
        sed -i "s|your_mongodb_uri|${{ secrets.MONGODB_URI }}|g" app.yaml
        sed -i "s|your_lichess_token|${{ secrets.LICHESS_TOKEN }}|g" app.yaml
        sed -i "s|your_jwt_secret|${{ secrets.JWT_SECRET }}|g" app.yaml
        sed -i "s|your_frontend_url|${{ secrets.FRONTEND_URL }}|g" app.yaml

    - name: Create App Engine application
      run: |
        gcloud app create --region=us-central || true

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --quiet 