name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v2

    - name: Google Auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
        project_id: '${{ secrets.GCP_PROJECT_ID }}'
        create_credentials_file: true
        export_environment_variables: true

    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v2.1.4
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'beta,app-engine-python'

    - name: Grant Storage Permissions
      run: |
        # Grant Storage Admin role to the service account
        gcloud projects add-iam-policy-binding ${{ secrets.GCP_PROJECT_ID }} \
          --member="serviceAccount:lichess-connector-account@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com" \
          --role="roles/storage.admin"
        
        # Grant Storage Object Viewer role
        gcloud projects add-iam-policy-binding ${{ secrets.GCP_PROJECT_ID }} \
          --member="serviceAccount:lichess-connector-account@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com" \
          --role="roles/storage.objectViewer"
        
        # Grant Storage Object Creator role
        gcloud projects add-iam-policy-binding ${{ secrets.GCP_PROJECT_ID }} \
          --member="serviceAccount:lichess-connector-account@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com" \
          --role="roles/storage.objectCreator"

    - name: Verify authentication
      run: |
        gcloud auth list
        gcloud config list project
        gcloud info

    - name: Update app.yaml with secrets
      run: |
        sed -i "s|your_mongodb_uri|${{ secrets.MONGODB_URI }}|g" app.yaml
        sed -i "s|your_lichess_token|${{ secrets.LICHESS_TOKEN }}|g" app.yaml
        sed -i "s|your_jwt_secret|${{ secrets.JWT_SECRET }}|g" app.yaml
        sed -i "s|your_frontend_url|${{ secrets.FRONTEND_URL }}|g" app.yaml

    - name: Deploy to App Engine
      run: |
        echo "Starting deployment..."
        gcloud app deploy app.yaml --quiet --project=${{ secrets.GCP_PROJECT_ID }}
        echo "Deployment completed." 