name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v2

    - name: Setup GCP Service Account
      run: |
        echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > ${{ github.workspace }}/gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/gcp-key.json" >> $GITHUB_ENV

    - name: Google Auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
        project_id: '${{ secrets.GCP_PROJECT_ID }}'
        create_credentials_file: true

    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v2.1.4
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'beta,app-engine-python'

    - name: Verify authentication
      run: |
        gcloud auth list
        gcloud config list project
        gcloud info

    - name: Update app.yaml with secrets
      run: |
        sed -i "s|your_mongodb_uri|${{ secrets.MONGODB_URI }}|g" app.yaml
        sed -i "s|your_lichess_token|${{ secrets.LICHESS_TOKEN }}|g" app.yaml
        sed -i "s|your_jwt_secret|${{ secrets.JWT_SECRET }}|g" app.yaml
        sed -i "s|your_frontend_url|${{ secrets.FRONTEND_URL }}|g" app.yaml

    - name: Enable necessary APIs
      run: |
        gcloud services enable appengine.googleapis.com
        gcloud services enable cloudbuild.googleapis.com

    - name: Deploy to App Engine
      run: |
        echo "Starting deployment..."
        gcloud app deploy app.yaml --quiet --project=${{ secrets.GCP_PROJECT_ID }}
        echo "Deployment completed."

    - name: Cleanup
      if: always()
      run: |
        rm -f ${{ github.workspace }}/gcp-key.json 